version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:28:b6:cb:12:62:a0:0c:66:f7:b3:fc:0d:9e:46:77"
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - run: 
          name: node-pre-gyp
          command: 'sudo npm install node-pre-gyp -g'
      - run: 
          name: mocha global
          command: 'sudo npm install mocha@7 -g'
      - run: 
          name: install tbb2 w/ cmake
          command: 'sudo apt-get install cmake cmake-curses-gui g++ build-essential libtbb2'
      - run: 
          name: go to node-occ root dir.
          command: 'cd ~/project/ && ls'
      - run: 
          name: node bash script for linux
          command: 'bash ./prepare_node.sh'
      - run: 
          name: export occt package name
          command: 'export OCCT_PACKAGE=occt-7.4.0'
      - run:
          name: libs export
          command: 'export LD_LIBRARY_PATH=`pwd`/${OCCT_PACKAGE}/lib:$LD_LIBRARY_PATH'
      - run:
          name: final tests
          command: 'make test'
      - store_artifacts:
          path: /home/circleci/project/build
