version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "56:b5:cb:a1:71:be:d4:a6:62:8a:36:6e:a6:43:a0:ed"
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - run:
          name: build-from-source
          command: npm install --build-from-source
      - store_artifacts:
          path: /home/circleci/project/build
