version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:28:b6:cb:12:62:a0:0c:66:f7:b3:fc:0d:9e:46:77"
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - run:
          name: build-from-source
          commands: 
            steps:
              -run: sudo apt-get install nodejs npm
              -run: sudo npm install node-pre-gyp -g
              -run: sudo npm install mocha@7 -g
              -run: sudo apt-get install cmake cmake-curses-gui g++ build-essential libtbb2
              -run: git clone --recursive https://github.com/antonymarion/node-occ.git
              -run: cd node-occ
              -run: bash ./prepare_node.sh
              -run: export OCCT_PACKAGE=occt-7.4.0
              -run: export LD_LIBRARY_PATH=`pwd`/${OCCT_PACKAGE}/lib:$LD_LIBRARY_PATH
              -run: npm install --build-from-source
              -run: make test
      - store_artifacts:
          path: /home/circleci/project/build
