version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - run:
          name: build-from-source
          command: npm install --build-from-source
      - store_artifacts:
          path: /home/circleci/project/build
